"""Threads for FSM execution and data collection from the Bpod hardware."""

import logging
import struct
import threading
import time
from collections.abc import Callable, Collection
from enum import IntEnum, auto
from queue import SimpleQueue
from typing import get_args

import numpy as np
import numpy.typing as npt
import polars as pl

from bpod_core.bpod.structs import (
    BpodEventType,
    BpodEventUnion,
    EventInput,
    EventOutput,
    EventStateEnd,
    EventStateStart,
    EventTrialEnd,
    EventTrialEndControl,
    EventTrialStart,
    RawEvent,
    RawSoftcode,
    StateMachineLookup,
    TimeReferences,
    _InputEvents,
)
from bpod_core.com import ExtendedSerial
from bpod_core.constants import STRUCT_UINT32_LE

logger = logging.getLogger(__name__)

_TIMING_VIOLATION_THRESHOLD_US = 1_000
"""Threshold for logging timing violations in microseconds."""

_INITIAL_BUFFER_SIZE = 2048
"""Initial size of the event buffer in EventThread."""

_OUTPUT_ID_OFFSET = 1000
"""Event ID offset for output action events."""

_EVENT_DTYPE = np.dtype(
    [
        ('time', 'datetime64[us]'),
        ('event_id', np.int16),
        ('state_id', np.int16),
        ('value', np.int16),
    ]
)
"""Structured NumPy dtype for recorded events."""


class _EventID(IntEnum):
    """Enum for event codes."""

    STOP_SENTINEL = -100
    """Sentinel value for stopping threads."""
    EXIT = 255
    """Exit code for the Bpod."""
    START_FSM = auto()
    START_STATE = auto()
    END_STATE = auto()
    END_FSM_CYCLES = auto()
    END_FSM_MICROS = auto()


_SYNTHETIC_EVENT_TYPES: dict[_EventID, str] = {
    _EventID.START_FSM: 'TrialStart',
    _EventID.START_STATE: 'StateStart',
    _EventID.END_STATE: 'StateEnd',
    _EventID.END_FSM_CYCLES: 'TrialEnd',
    _EventID.END_FSM_MICROS: 'TrialEndControl',
}
"""Names for synthetic events generated by :class:`ReadThread`."""

_EVENT_TYPE_ENUM = pl.Enum(get_args(BpodEventType))
"""Polars Enum dtype for the ``type`` column in trial DataFrames.

Built from :data:`~bpod_core.bpod.structs.BpodEventType`.
"""

_TRIAL_DATA_SCHEMA = {
    'time': pl.Datetime('us', time_zone='UTC'),
    'trial': pl.UInt16,
    'state machine': pl.Categorical,
    'state': pl.Categorical,
    'type': _EVENT_TYPE_ENUM,
    'event': pl.Categorical,
    'channel': pl.Categorical,
    'value': pl.UInt8,
}
"""Column schema for trial DataFrames returned by :meth:`~bpod_core.bpod.Bpod.get_data`
and :meth:`~bpod_core.bpod.Bpod.peek_data`."""

_SYNTHETIC_EVENT_LOOKUP = pl.DataFrame(
    {
        'event_id': pl.Series(list(_SYNTHETIC_EVENT_TYPES), dtype=pl.Int16),
        'type': pl.Series(
            list(_SYNTHETIC_EVENT_TYPES.values()), dtype=_EVENT_TYPE_ENUM
        ),
        'event': pl.Series([None] * len(_SYNTHETIC_EVENT_TYPES), dtype=pl.Null),
        'channel': pl.Series([None] * len(_SYNTHETIC_EVENT_TYPES), dtype=pl.Null),
        'default_value': pl.Series(
            [None] * len(_SYNTHETIC_EVENT_TYPES), dtype=pl.UInt8
        ),
    }
)
"""Pre-built lookup rows for synthetic FSM events (stable across all sessions)."""


def _build_event_lookup(
    input_events: _InputEvents, action_names: list[str]
) -> pl.DataFrame:
    """Build the event metadata lookup DataFrame.

    Parameters
    ----------
    input_events : _InputEvents
        Hardware-level input event names and their source channels.
    action_names : list of str
        Names of all output channels, indexed by action ID.

    Returns
    -------
    pl.DataFrame
        DataFrame with columns ``event_id`` (Int16), ``type`` (Enum),
        ``event`` (Categorical), ``channel`` (Categorical), and
        ``default_value`` (UInt8, null if no pre-defined value),
        covering input events, synthetic events, and output actions.
    """
    output_ids = [_OUTPUT_ID_OFFSET + i for i in range(len(action_names))]
    input_lookup = pl.DataFrame(
        {
            'event_id': pl.Series(range(len(input_events.names)), dtype=pl.Int16),
            'type': pl.Series(
                ['InputEvent'] * len(input_events.names), dtype=_EVENT_TYPE_ENUM
            ),
            'event': pl.Series(input_events.names, dtype=pl.Categorical),
            'channel': pl.Series(input_events.channels, dtype=pl.Categorical),
            'default_value': pl.Series(input_events.values, dtype=pl.UInt8),
        }
    )
    output_lookup = pl.DataFrame(
        {
            'event_id': pl.Series(output_ids, dtype=pl.Int16),
            'type': pl.Series(
                ['OutputAction'] * len(action_names), dtype=_EVENT_TYPE_ENUM
            ),
            'event': pl.Series([None] * len(action_names), dtype=pl.Categorical),
            'channel': pl.Series(action_names, dtype=pl.Categorical),
            'default_value': pl.Series([None] * len(action_names), dtype=pl.UInt8),
        }
    )
    return pl.concat([input_lookup, _SYNTHETIC_EVENT_LOOKUP, output_lookup])


class ReadThread(threading.Thread):
    """Serial reader thread for one Bpod trial.

    Runs for the lifetime of a single trial. Reads the hardware confirmation, then
    enters a tight loop parsing the two-byte opcode packets the Bpod streams over
    serial:

    - **Opcode 1** – hardware events: reads ``param`` event bytes followed by a 4-byte
      ``uInt32`` cycle count. Timestamps are derived as
      ``start_micros_us + n_cycles * cycle_period_us`` and each event is pushed to
      ``queue_events`` as a :class:`~bpod_core.bpod.structs.RawEvent`. An ``EXIT``
      byte (255) triggers :meth:`stop`.
    - **Opcode 2** – softcodes: the ``param`` byte (1-indexed) is forwarded to
      ``queue_softcodes``.

    **Hot-loop optimisations:**

    - Two fixed :class:`bytearray` buffers (``opcode_buf``: 2 bytes,
      ``event_data_buf``: 259 bytes) are allocated once before the loop.
      ``serial.readinto()`` writes directly into them — no per-packet allocation.
    - A :class:`memoryview` over ``event_data_buf`` allows zero-copy slicing for
      both the variable-length event payload and the trailing cycle-count word.
    - ``struct.unpack_from()`` unpacks the cycle count in-place from the memoryview
      without creating an intermediate bytes object.
    - Frequently accessed instance attributes (``serial``, queues,
      ``cycle_period_us``) are cached as locals before the loop to avoid repeated
      ``LOAD_ATTR`` bytecode overhead.

    After the loop, the thread reads the 12-byte end-of-trial packet (``uInt32`` cycle
    count + ``uInt64`` µs timestamp, unpacked via :attr:`_struct_exit`) and enqueues
    :attr:`~_EventID.END_FSM_CYCLES` and :attr:`~_EventID.END_FSM_MICROS`.
    A :attr:`~_EventID.STOP_SENTINEL` is always enqueued in ``finally`` so
    :class:`EventThread` can detect termination regardless of how the trial ended.

    Parameters
    ----------
    serial : ExtendedSerial
        The serial connection to the Bpod device.
    state_machine_hash : bytes
        The hash of the state machine.
    trial : int
        Zero-based trial index.
    cycle_period_us : int
        The cycle period of the Bpod device in microseconds.
    queue_events : SimpleQueue[RawEvent]
        Queue for storing events.
    queue_softcodes : SimpleQueue[RawSoftcode]
        Queue for storing softcodes.
    """

    _struct_exit = struct.Struct('<IQ')

    def __init__(
        self,
        *,
        serial: ExtendedSerial,
        state_machine_hash: bytes,
        trial: int,
        cycle_period_us: int,
        queue_events: SimpleQueue[RawEvent],
        queue_softcodes: SimpleQueue[RawSoftcode],
    ) -> None:
        super().__init__(name='ReadThread', daemon=True)
        self._serial = serial
        self._stop_event = threading.Event()
        self._fsm_hash = state_machine_hash.hex()
        self._trial = trial
        self._cycle_period_us = cycle_period_us
        self._queue_events = queue_events
        self._queue_softcodes = queue_softcodes

    def stop(self) -> None:
        """Signal the FSM thread to stop after the current state cycle."""
        self._stop_event.set()

    def run(self) -> None:
        """Execute the ReadThread."""
        try:
            # confirm the state machine
            if not self._serial.read_bool():
                raise RuntimeError(
                    f'State machine #{self._trial} not confirmed by Bpod'
                )
            logger.info(
                'Starting state machine %s / trial #%d', self._fsm_hash, self._trial
            )

            # read the starting timestamps of the state machine
            # we do this early to get an accurate timestamp for the system clock
            start_micros_us = self._serial.read_uint64()

            # assign members to local variables to avoid repeated attribute lookups
            serial = self._serial
            cycle_period_us = self._cycle_period_us
            q_events = self._queue_events
            q_softcodes = self._queue_softcodes

            # create buffers / memoryview for repeated serial reads
            opcode_buf = bytearray(2)  # buffer for opcodes
            event_data_buf = bytearray(259)  # max 255 events + 4 bytes for n_cycles
            event_data_view = memoryview(event_data_buf)

            # handle events: start of state machine, start of state
            q_events.put(RawEvent(start_micros_us, _EventID.START_FSM))
            q_events.put(RawEvent(start_micros_us, _EventID.START_STATE))

            # tracks the most recent Bpod cycle timestamp for softcode attribution
            last_micros_us = start_micros_us

            # enter the reading loop
            while not self._stop_event.is_set():
                # TODO: thread is blocked by readinto()
                #
                # Options:
                # a) use serial timeout,
                # b) while serial.in_waiting() < 2:
                #        if self._stop_event.wait(timeout=0.01):
                #            break
                # c) thread entirely controlled by bpod (no _stop_event required)
                #
                # readinto returns number of bytes read, so we can use it to check for
                # timeout

                # read the next two opcodes
                serial.readinto(opcode_buf)
                opcode, param = opcode_buf

                # HANDLE EVENTS
                if opcode == 1:
                    # read `param` event bytes + 4 bytes for n_cycles (uInt32)
                    serial.readinto(event_data_view[: param + 4])

                    # unpack the cycle count and derive the event timestamp
                    (n_cycles,) = STRUCT_UINT32_LE.unpack_from(event_data_view, param)
                    derived_micros_us = start_micros_us + n_cycles * cycle_period_us
                    last_micros_us = derived_micros_us

                    # hand events over to the EventThread
                    for event in event_data_view[:param]:
                        if event == _EventID.EXIT:
                            self.stop()
                            break
                        q_events.put(RawEvent(derived_micros_us, event))

                # HANDLE SOFTCODES
                elif opcode == 2:
                    received_ns = time.perf_counter_ns()
                    softcode = param - 1  # subtract 1 for zero-based indexing

                    # add softcode to the softcode queue
                    # note: while incoming softcodes do not carry a timestamp, they are
                    #       always preceded by a state change in the same cycle. We can
                    #       thus use the last available timestamp for the softcode.
                    q_softcodes.put(RawSoftcode(softcode, received_ns, last_micros_us))

                # HANDLE UNKNOWN OPCODES
                else:
                    raise RuntimeError(f'Received unknown opcode from Bpod: {opcode}')

            # the Bpod sends two values after exiting the state machine trial:
            # 1) n_cycles - the number of hardware timer callbacks executed (uInt32)
            # 2) bpod_micros - the microsecond count at the end of the trial (uInt64)
            serial.readinto(event_data_view[:12])
            n_cycles, end_micros_us = self._struct_exit.unpack_from(event_data_view)

            # verify hardware timer reliability: warn if cycle-based and micros-based
            # trial durations diverge beyond the threshold.
            duration_micros_us = end_micros_us - start_micros_us
            duration_cycles_us = n_cycles * cycle_period_us
            duration_discrepancy_us = duration_cycles_us - duration_micros_us
            if abs(duration_discrepancy_us) > _TIMING_VIOLATION_THRESHOLD_US:
                average_cycle_period_us = (
                    (duration_micros_us / n_cycles) if n_cycles else float('nan')
                )
                logger.warning(
                    'Violation of hardware timing guarantees. Trial was %d µs %s than '
                    'expected. Average cycle period: %0.3f µs (expected: %0.3f µs).',
                    abs(duration_discrepancy_us),
                    'longer' if duration_discrepancy_us < 0 else 'shorter',
                    average_cycle_period_us,
                    cycle_period_us,
                )

            # enqueue end-of-trial event
            derived_micros = start_micros_us + duration_cycles_us
            q_events.put(RawEvent(derived_micros, _EventID.END_FSM_CYCLES))
            q_events.put(RawEvent(end_micros_us, _EventID.END_FSM_MICROS))

        finally:
            self._queue_events.put(RawEvent(0, _EventID.STOP_SENTINEL))
            logger.debug(
                'Exiting state machine %s / trial #%d', self._fsm_hash, self._trial
            )

    @property
    def trial_number(self) -> int:
        """The zero-based trial number."""
        return self._trial


class EventThread(threading.Thread):
    """Consumer thread that processes hardware events and builds the trial DataFrame.

    Runs for the duration of one trial. :class:`ReadThread` feeds raw
    :class:`~bpod_core.bpod.structs.RawEvent` items into :attr:`queue`; ``EventThread``
    drains that queue, advances the FSM state, and records every event — inputs, state
    transitions, and output actions — into an internal buffer.

    When the trial ends (``STOP_SENTINEL`` received), the buffer is converted to a
    :class:`polars.LazyFrame` and pushed onto *data_queue* for the caller to collect via
    :meth:`~bpod_core.bpod.Bpod.get_data`.

    **Buffer design**: events are appended to a pre-allocated NumPy structured array
    (``_EVENT_DTYPE``) that doubles in size when full. The buffer is only written at
    index ``_n_events`` before that counter is incremented, so indices
    ``0.._n_events-1`` are immutable once written.

    **Thread safety**: :meth:`peek_data` may be called from another thread while the
    trial is running. It copies the buffer view before passing it to Polars, ensuring a
    consistent snapshot.

    Parameters
    ----------
    trial : int
        Zero-based trial index, used to populate the ``trial`` column.
    fsm : StateMachineLookup
        Compiled state machine data for this trial.
    data_queue : SimpleQueue of LazyFrame
        Queue to push the completed trial DataFrame into.
    event_lookup : polars.DataFrame
        Pre-built event metadata lookup, see :func:`_build_event_lookup`.
    action_names : list of str
        Names of all output channels, indexed by action ID.
    time_reference : TimeReferences
        Reference values for performance counters.
    publish : Callable
        Called with one :class:`~bpod_core.bpod.structs.BpodEventUnion` message per
        recorded hardware event; return values are ignored. Publishing is best-effort:
        exceptions are logged but do not interrupt trial recording.
    publish_gate : Callable
        Zero-argument callable consulted before resolving and publishing each message;
        returning False skips that work entirely. Checked per message, so a subscriber
        appearing mid-trial picks up the stream from there.
    """

    queue: SimpleQueue[RawEvent]
    """Per-trial event queue shared with :class:`ReadThread`."""

    def __init__(
        self,
        *,
        trial: int,
        fsm: StateMachineLookup,
        data_queue: SimpleQueue[pl.LazyFrame],
        event_lookup: pl.DataFrame,
        action_names: list[str],
        time_reference: TimeReferences,
        publish: Callable[[BpodEventUnion], object],
        publish_gate: Callable[[], bool],
    ) -> None:
        super().__init__(name='EventThread', daemon=True)
        self.queue: SimpleQueue[RawEvent] = SimpleQueue()
        self._trial = trial
        self._data_queue = data_queue
        self._state_transition_matrix = fsm.state_transition_matrix
        self._use_back_op = fsm.use_back_op
        self._time_reference = time_reference
        self._publish = publish
        self._publish_gate = publish_gate
        self._buffer: npt.NDArray = np.empty(_INITIAL_BUFFER_SIZE, dtype=_EVENT_DTYPE)
        self._n_events: int = 0
        self._check_trigger = threading.Event()
        self._event_lookup = event_lookup.lazy()
        self._state_names = fsm.state_names
        self._state_lookup = fsm.state_lookup
        self._fsm_hash_str = fsm.fsm_hash.hex()

        # pre-compute action index map for fast lookup in the hot loop
        action_index_map = {name: i for i, name in enumerate(action_names)}
        self._state_action_indices: list[dict[int, int]] = [
            {action_index_map[k]: v for k, v in d.items()} for d in fsm.state_actions
        ]
        # TTL and PWM outputs are implicitly reset to 0 at each state transition
        self._resettable_indices: frozenset[int] = frozenset(
            i for i, name in enumerate(action_names) if name.startswith(('TTL', 'PWM'))
        )

        # pre-compute event metadata for resolving published messages in the hot
        # loop; covers input events, synthetic events, and output actions alike
        self._event_info: dict[
            int, tuple[BpodEventType, str | None, str | None, int | None]
        ] = {
            row['event_id']: (
                row['type'],
                row['event'],
                row['channel'],
                row['default_value'],
            )
            for row in event_lookup.iter_rows(named=True)
        }
        self._n_published: int = 0

    def stop(self) -> None:
        """Signal the FSM thread to stop."""
        self.queue.put(RawEvent(micros_us=0, event_id=_EventID.STOP_SENTINEL))

    def _append(
        self,
        time_bpod_us: int,
        event_index: int,
        state_id: int = 0,
        value: int = -1,
    ) -> None:
        """Append an event to the buffer, growing it if necessary."""
        if self._n_events == len(self._buffer):
            new_buf = np.empty(len(self._buffer) * 2, dtype=_EVENT_DTYPE)
            new_buf[: self._n_events] = self._buffer
            self._buffer = new_buf
        self._buffer[self._n_events] = (
            time_bpod_us,
            event_index,
            state_id,
            value,
        )
        self._n_events += 1

        # publish the event using ZeroMQ
        try:
            # Skip resolution and struct construction if nobody is listening.
            if not self._publish_gate():
                return

            kind, event, channel, default_value = self._event_info[event_index]
            message: BpodEventUnion
            match kind:
                case 'InputEvent' if event is not None:
                    message = EventInput(
                        time_us=time_bpod_us,
                        event=event,
                        channel=channel,
                        value=default_value if value == -1 else value,
                    )
                case 'OutputAction' if channel is not None:
                    message = EventOutput(
                        time_us=time_bpod_us, channel=channel, value=value
                    )
                case 'StateStart':
                    message = EventStateStart(
                        time_us=time_bpod_us, state=self._state_lookup[state_id]
                    )
                case 'StateEnd':
                    message = EventStateEnd(
                        time_us=time_bpod_us, state=self._state_lookup[state_id]
                    )
                case 'TrialStart':
                    message = EventTrialStart(
                        time_us=time_bpod_us,
                        trial=self._trial,
                        fsm_hash=self._fsm_hash_str,
                    )
                case 'TrialEnd':
                    message = EventTrialEnd(time_us=time_bpod_us, trial=self._trial)
                case 'TrialEndControl':
                    message = EventTrialEndControl(
                        time_us=time_bpod_us,
                        trial=self._trial,
                        n_events=self._n_published + 1,
                    )
                case _:
                    logger.warning('Not publishing unknown event type: %s', kind)
                    return
            self._publish(message)
            self._n_published += 1
        except Exception:
            logger.exception('Failed to publish trial event')

    def run(self) -> None:
        """Execute the EventThread."""
        event_queue = self.queue
        state_transition_matrix = self._state_transition_matrix
        state_action_indices = self._state_action_indices
        resettable_indices = self._resettable_indices
        use_back_op = self._use_back_op
        target_exit = state_transition_matrix.shape[0]
        target_back = 255
        stateless_events = (
            _EventID.START_FSM,
            _EventID.END_FSM_CYCLES,
            _EventID.END_FSM_MICROS,
        )
        current_state = 0
        previous_state = 0
        active_outputs: dict[int, int] = {}  # resettable outputs currently non-zero

        base_time_bpod_us = self._time_reference.reset_system_time_ns // 1000

        try:
            while True:
                # get the next event
                bpod_count_us, event_index = event_queue.get()

                # check if we need to stop the thread
                if event_index == _EventID.STOP_SENTINEL:
                    break

                # convert relative timestamps to absolute timestamps
                t_bpod_us = base_time_bpod_us + bpod_count_us

                # implicitly end the current state and reset active outputs
                # before the TrialEnd row
                if event_index == _EventID.END_FSM_CYCLES:
                    if current_state >= 0:
                        self._append(
                            t_bpod_us, _EventID.END_STATE, state_id=current_state
                        )
                    for idx in sorted(active_outputs):
                        output_id = _OUTPUT_ID_OFFSET + idx
                        self._append(t_bpod_us, output_id, state_id=-1, value=0)
                    active_outputs.clear()

                # append the event to the buffer
                state = -1 if event_index in stateless_events else current_state
                self._append(t_bpod_us, event_index, state_id=state)
                if event_index == _EventID.START_STATE:
                    self._check_trigger.set()

                # handle state transitions
                if event_index < 255:
                    if current_state < 0:  # FSM already exited - record event only
                        continue
                    # define the target state based on the state transition matrix
                    target_state = int(
                        state_transition_matrix[current_state][event_index]
                    )
                    if target_state == current_state:  # no transition
                        continue
                    if target_state == target_exit:  # state exited without a successor
                        self._append(
                            t_bpod_us,
                            _EventID.END_STATE,
                            state_id=current_state,
                        )
                        current_state = -1
                        continue
                    if target_state == target_back and use_back_op:  # >back operator
                        target_state = previous_state

                    # record end of current state, advance, record start of next
                    self._append(t_bpod_us, _EventID.END_STATE, state_id=current_state)
                    previous_state = current_state
                    current_state = target_state
                    self._append(
                        t_bpod_us, _EventID.START_STATE, state_id=current_state
                    )
                    self._check_trigger.set()

                # record output actions (initial state & after state transitions):
                # absent channels are reset (0); others get their new value.
                if event_index < 255 or event_index == _EventID.START_STATE:
                    new_actions = state_action_indices[current_state]
                    for idx in sorted(active_outputs.keys() | new_actions.keys()):
                        val = new_actions.get(idx, 0)
                        output_id = _OUTPUT_ID_OFFSET + idx
                        self._append(
                            t_bpod_us,
                            output_id,
                            state_id=current_state,
                            value=val,
                        )
                    active_outputs.clear()
                    for idx, val in new_actions.items():
                        if idx in resettable_indices and val > 0:
                            active_outputs[idx] = val  # noqa: PERF403
        finally:
            self._enqueue_data()
            self._check_trigger.set()

    @property
    def _buffer_view(self) -> npt.NDArray:
        """Return a view of the buffer."""
        n = self._n_events
        return self._buffer[:n]

    def _to_lazyframe(self, data: npt.NDArray) -> pl.LazyFrame:
        """Convert a buffer array to a trial LazyFrame."""
        return (
            pl.from_numpy(data)
            .lazy()
            .join(self._event_lookup, on='event_id', how='left')
            .with_columns(
                pl.col('state_id')
                .replace_strict(
                    self._state_lookup, return_dtype=pl.Categorical, default=None
                )
                .alias('state')
            )
            .with_columns(
                pl.col('time').dt.replace_time_zone('UTC'),
                pl.lit(self._trial).cast(pl.UInt16).alias('trial'),
                pl.lit(self._fsm_hash_str).cast(pl.Categorical).alias('state machine'),
                pl.coalesce(
                    pl.col('value').replace(-1, None),
                    pl.col('default_value'),
                )
                .cast(pl.UInt8)
                .alias('value'),
            )
            .select(list(_TRIAL_DATA_SCHEMA))
        )

    def peek_data(
        self,
        trigger_states: Collection[str] | None = None,
    ) -> pl.LazyFrame:
        """Return a snapshot of events recorded so far as a :class:`polars.LazyFrame`.

        Safe to call from a different thread while the trial is running. The returned
        DataFrame reflects events up to the moment ``_n_events`` was read; one in-flight
        event may be missed.

        Parameters
        ----------
        trigger_states : Collection of str, optional
            Block until at least one of the given states has been entered. If the trial
            ends before any of the states have been entered, returns whatever was
            recorded.

        Returns
        -------
        LazyFrame
            A snapshot of the recorded events.

        Raises
        ------
        ValueError
            If one or several of the trigger states are not part of the state machine.
        """
        if trigger_states is None:
            return self._to_lazyframe(self._buffer_view.copy())
        if unknown_states := (set(trigger_states) - set(self._state_names)):
            pt1 = f'Unknown trigger state{"s" if len(unknown_states) > 1 else ""}: '
            pt2 = ', '.join([f"'{u}'" for u in sorted(unknown_states)])
            raise ValueError(pt1 + pt2)
        target_ids = [i for i, s in enumerate(self._state_names) if s in trigger_states]
        while True:
            self._check_trigger.clear()
            view = self._buffer_view
            if np.any(np.isin(view['state_id'], target_ids)) or not self.is_alive():
                return self._to_lazyframe(view.copy())
            self._check_trigger.wait()

    def _enqueue_data(self) -> None:
        """Enqueue recorded events as a :class:`polars.LazyFrame`."""
        self._data_queue.put(self._to_lazyframe(self._buffer_view))


class SoftcodeThread(threading.Thread):
    """Consumer thread that executes softcode handlers sent from the Bpod.

    :class:`ReadThread` feeds :class:`~bpod_core.bpod.structs.RawSoftcode` items into
    :attr:`queue`; ``SoftcodeThread`` drains that queue and calls the registered handler
    for each softcode.

    The handler can be swapped at any time via :meth:`set_handler` without restarting
    the thread — the new handler takes effect on the next softcode.

    Handler exceptions are caught, logged, and execution continues.
    """

    queue: SimpleQueue[RawSoftcode]
    """Softcode queue shared with :class:`ReadThread`."""

    def __init__(
        self,
        *,
        softcode_handler: Callable[[int], None] | None,
    ) -> None:
        super().__init__(name='SoftcodeThread', daemon=True)
        self.queue: SimpleQueue[RawSoftcode] = SimpleQueue()
        self._softcode_handler = softcode_handler
        self._idle = threading.Event()
        self._idle.set()
        self._pc_base_ns: int = 0  # perf_counter_ns equivalent of session clock t=0

    def drain(self) -> None:
        """Block until the queue is empty and any running handler has returned."""
        if not self._idle.is_set():
            logger.warning('Waiting for softcodes to be processed ...')
        self._idle.wait()

    def set_handler(self, handler: Callable[[int], None] | None) -> None:
        """Set the softcode handler, taking effect on the next received softcode."""
        self._softcode_handler = handler

    def set_time_reference(self, time_ref: TimeReferences) -> None:
        """Update the session clock reference used for Bpod-relative latency logging."""
        self._pc_base_ns = (
            time_ref.reset_system_time_ns
            - time_ref.init_system_time_ns
            + time_ref.init_perf_counter_ns
        )

    def run(self) -> None:
        """Execute the SoftcodeThread."""
        queue = self.queue

        # enter the reading loop
        while True:
            softcode, received_ns, micros_us = queue.get()
            self._idle.clear()
            handler = self._softcode_handler
            if handler is not None:
                try:
                    start_ns = time.perf_counter_ns()
                    handler(softcode)
                    if logger.isEnabledFor(logging.DEBUG):
                        done_ns = time.perf_counter_ns()
                        fire_ns = self._pc_base_ns + micros_us * 1000
                        logger.debug(
                            "'%s(%d)': "
                            'latency=%.3f ms, dispatch=%.3f ms, duration=%.3f ms',
                            getattr(handler, '__name__', 'unknown'),
                            softcode,
                            (start_ns - fire_ns) / 1e6,
                            (start_ns - received_ns) / 1e6,
                            (done_ns - start_ns) / 1e6,
                        )
                except Exception as e:
                    logger.exception(
                        "Error calling '%s(%d)'",
                        getattr(handler, '__name__', 'unknown'),
                        softcode,
                        exc_info=e,
                    )
            else:
                logger.warning(
                    'Received softcode %d from Bpod but no handler is defined', softcode
                )
            if queue.empty():
                self._idle.set()
