[tox]
requires = tox >= 4.25.0
env_list = ruff, typing, clean, py3{10-13}{posargs}, finalize{posargs}

[testenv]
dependency_groups = test
runner = uv-venv-lock-runner
setenv =
   COVERAGE_FILE = .coverage.{py_dot_ver}
   COVERALLS_FLAG_NAME = {on_platform}_python{py_dot_ver}
passenv =
   GITHUB_*
   COVERALLS_*

[testenv:ruff]
description = run ruff linter
dependency_groups = lint
commands =
   ruff check
   ruff format --check
skip_install = true

[testenv:typing]
description = run mypy type checker
dependency_groups = typing
commands = mypy
skip_install = true

[testenv:clean]
description = clean up coverage files
commands = coverage erase

[testenv:py3{10-13}]
description = run pytest on python {py_dot_ver}
depends: clean
commands =
   pytest

[testenv:py3{10-13}-ci]
description = run pytest on python {py_dot_ver} (CI)
depends: clean
dependency_groups = test, ci
commands =
   pytest
   coverage xml --data-file={env:COVERAGE_FILE} -o {env:COVERAGE_FILE}.xml
   coveralls --submit={env:COVERAGE_FILE}.xml --service=github-actions

[testenv:finalize]
description = combine coverage files
depends: py3{10-13}{posargs}
setenv =
   COVERAGE_FILE = .coverage
commands = coverage combine

[testenv:finalize-ci]
description = close parallel builds (CI)
depends: py3{10-13}{posargs}
dependency_groups = ci
commands = coveralls --finish
